### ISSUE TITLE
seems to break youtube

### ISSUE THREAD

**Issue by borrel** [addyosmani/cssprettifier-bookmarklet#3]
hi,
# steps

go to a youtube video
open dev console
paste the js-url in the address bar 
# expected

butified css
# actual result

youtube gets messed up

**Comment by addyosmani** [comment]
Please note that you need to be using View Source and then running the bookmarklet against this. See the updated readme for usage https://github.com/addyosmani/cssprettifier-bookmarklet/blob/master/README.md
